const BaseOfficialPropertyDataProvider = require("./BaseOfficialPropertyDataProvider");

const toStableNumber = (value, min, max) => {
  const seed = String(value || "");
  const hash = seed.split("").reduce((sum, char, index) => {
    return sum + char.charCodeAt(0) * (index + 1);
  }, 0);

  return min + (hash % (max - min + 1));
};

const buildRegistryRecordId = (countryCode, propertyId) => {
  const suffix = String(propertyId || "")
    .replace(/[^a-zA-Z0-9]/g, "")
    .slice(-8)
    .toUpperCase();

  return `${String(countryCode || "").toUpperCase()}-${suffix || "DUMMY"}`;
};

class StubOfficialPropertyDataProvider extends BaseOfficialPropertyDataProvider {
  constructor(config) {
    super({
      ...config,
      mode: "stub",
    });
  }

  async checkProperty(property) {
    const hasTitleDeed = Array.isArray(property.documents)
      ? property.documents.some((document) => document?.type === "title_deed")
      : false;
    const hasAddress = Boolean(
      property.fullAddress && property.city && property.country,
    );
    const hasCoordinates = Boolean(
      property.locationPin?.lat && property.locationPin?.lng,
    );
    const confidenceScore = toStableNumber(property._id || property.id, 78, 96);
    const registryRecordId = buildRegistryRecordId(
      this.countryCode,
      property._id || property.id,
    );

    const checks = [
      {
        key: "address_match",
        label: "Address match",
        status: hasAddress ? "match" : "review_required",
        detail: hasAddress
          ? "Property address structure looks complete for a future registry lookup."
          : "Address details should be completed before live registry validation.",
      },
      {
        key: "title_deed_document",
        label: "Title deed document",
        status: hasTitleDeed ? "match" : "missing",
        detail: hasTitleDeed
          ? "A title deed document exists in the uploaded file set."
          : "No title deed document was found in the uploaded files.",
      },
      {
        key: "map_coordinates",
        label: "Map coordinates",
        status: hasCoordinates ? "match" : "review_required",
        detail: hasCoordinates
          ? "Coordinates are available and can be used in future official lookups."
          : "Coordinates are missing or incomplete for registry-side verification.",
      },
      {
        key: "ownership_registry",
        label: "Ownership registry",
        status: "pending_integration",
        detail:
          "Live ownership verification will be connected once this country's official API credentials are available.",
      },
      {
        key: "encumbrance_screening",
        label: "Encumbrance screening",
        status: "pending_integration",
        detail:
          "Mortgage, lien, and annotation checks are stubbed until the live registry adapter is connected.",
      },
    ];

    const missingCriticalData = checks.some((check) => check.status === "missing");
    const overallStatus = missingCriticalData
      ? "manual_review_required"
      : "simulated_match";

    return {
      simulated: true,
      overallStatus,
      checkedAt: new Date().toISOString(),
      provider: this.getProviderInfo(),
      propertySnapshot: {
        id: String(property._id || property.id || ""),
        country: property.country,
        city: property.city,
        fullAddress: property.fullAddress,
        propertyType: property.propertyType,
      },
      registryRecord: {
        id: registryRecordId,
        confidenceScore,
        normalizedAddress: [property.fullAddress, property.city, property.country]
          .filter(Boolean)
          .join(", "),
        notes:
          "This registry record is generated by the stub adapter and should be replaced by live data later.",
      },
      summary: missingCriticalData
        ? "Dummy registry check completed. Some critical documents are still missing, so this property should stay in manual review."
        : "Dummy registry check completed. Basic property data looks structurally ready for a future live registry verification.",
      checks,
      recommendedActions: hasTitleDeed
        ? [
            "Compare the uploaded title deed with the address and owner identity documents.",
            "Keep this property in manual review until the live country registry adapter is connected.",
          ]
        : [
            "Request a title deed upload before publishing the property.",
            "Keep this property in manual review until missing documents are completed.",
          ],
      disclaimers: [
        "This response is simulated because the official API integration is not connected yet.",
        `${this.countryName} registry integration can be swapped in later without changing the admin UI flow.`,
      ],
    };
  }
}

module.exports = StubOfficialPropertyDataProvider;
